// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      watch: {
        stylus_stylesheets: {
          files: ['css/*.styl'],
          tasks: ['stylus']
        },
        coffeescripts: {
          files: ['wp-content/plugins/nbw/js/**/*.coffee'],
          tasks: ['coffee']
        },
        livereloads: {
          files: ['*.css', '*.html', '*.js'],
          options: {
            livereload: {
              port: 9001
            }
          }
        }
      },
      stylus: {
        compile: {
          options: {
            paths: ['./'],
            compress: true
          },
          files: 'css/style.styl',
          'wp-content/plugins/nbw/styles/admin_option.css': 'wp-content/plugins/nbw/styles/admin_option.styl'
        }
      },
      coffee: {
        compile: {
          options: {
            paths: ['./'],
            compress: true
          },
          files: {
            'wp-content/plugins/nbw/js/main.js': 'wp-content/plugins/nbw/js/main.coffee',
            'wp-content/plugins/nbw/js/admin_option.js': 'wp-content/plugins/nbw/js/admin_option.coffee'
          }
        }
      },
      exec: {
        upload_css: {
          cmd: 'scp wp-content/plugins/nbw/styles/main.css ssh_username@ssh_host.com:public_html/wp-content/plugins/nbw/styles/main.css'
        },
        upload_js: {
          cmd: 'scp wp-content/plugins/nbw/js/main.js ssh_username@ssh_host.com:public_html/wp-content/plugins/nbw/styles/main.js'
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-contrib-stylus');
    grunt.loadNpmTasks('grunt-contrib-coffee');
    grunt.loadNpmTasks('grunt-exec');
    return grunt.registerTask('default', ['watch']);
  };

}).call(this);

//# sourceMappingURL=gruntfile.js.map
